---

- name: Cloning 3xui repo
  become: true
  become_user: "{{user_install}}"
  git:
    repo: 'https://github.com/MHSanaei/3x-ui.git'
    dest: '/home/{{ user_install }}/x-ui'
    force: true
  when: user_install != "root"

- name: Cloning 3xui repo
  git:
    repo: 'https://github.com/MHSanaei/3x-ui.git'
    dest: '/{{ user_install }}/x-ui'
    force: true
  when: user_install == "root"


- name: Change docker compose file
  become: true
  become_user: "{{user_install}}"
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    regexp: '    hostname: yourhostname'
    line: '    hostname: {{user_domain}}'
  when: user_install != "root"

- name: Change docker compose file
  become: true
  become_user: "{{user_install}}"
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    regexp: '.*\$PWD\/cert\/*.*'
    line: '      - /etc/letsencrypt/:/etc/letsencrypt/'
  when: user_install != "root"


- name: Change docker compose file
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    regexp: '    hostname: yourhostname'
    line: '    hostname: {{user_domain}}'
  when: user_install != "root"

- name: Change docker compose file
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    regexp: '.*\$PWD\/cert\/*.*'
    line: '      - /etc/letsencrypt/:/etc/letsencrypt/'
  when: user_install != "root"

- name: Remove network_mode host from file
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    line: '    network_mode: host'
    state: absent

- name: Add ports on docker-compose file
  lineinfile:
    path: '/home/{{ user_install }}/x-ui/docker-compose.yml'
    line: "{{ item }}"
  loop:
    - '    ports:'
    - '      - 443:2053'
    - '      - 80:2053'

- name: Docker compose up
  become: true
  become_user: "{{user_install}}"
  docker_compose:
    project_src: '/home/{{ user_install }}/x-ui'
  register: output
  when: user_install != "root"

- name: Docker compose up
  docker_compose:
    project_src: '/{{ user_install }}/x-ui'
  register: output
  when: user_install == "root"
