---


- name: Default actions on all hosts
  hosts: all
  vars_prompt:
    - name: allowed_ports
      private: false
      prompt: "Enter allowed ports(seperate by commas)"
      default: 22,2053,80
    - name: user_install
      private: false
      prompt: "Install by which user?(default:root)"
      default: root
    - name: user_password
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7
      prompt: "Enter password for new user"
    - name: user_domain
      private: false
      prompt: "Enter your domain"
    - name: default_port
      private: false
      prompt: "Enter port of 3xui server"
      default: '2053'
  
  roles:
    - default
    - prerequisite
    - firewall
    - user
    - ray
    - certbot
